# Generated by Django 4.1.6 on 2023-02-17 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=70, unique=True, verbose_name='email')),
                ('token', models.DecimalField(decimal_places=2, default=0, max_digits=100000, verbose_name='token balance')),
                ('streak_number', models.IntegerField(default=0, verbose_name='streak number')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('profile_image', models.ImageField(blank=True, default=None, max_length=255, null=True, upload_to=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, verbose_name='title')),
                ('duration', models.IntegerField(default=0, verbose_name='movie duration')),
                ('description', models.TextField(default='', verbose_name='movie description')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='movie price')),
                ('image', models.ImageField(blank=True, default=None, max_length=255, null=True, upload_to=None, verbose_name='movie image')),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movies_watched', models.IntegerField(default=0)),
                ('movies_liked', models.IntegerField(default=0)),
                ('comment_counter', models.IntegerField(default=0)),
                ('likes_counter', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='subscribed_movies',
            field=models.ManyToManyField(blank=True, to='base.movie'),
        ),
    ]
