# Generated by Django 4.1.6 on 2023-02-19 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_user_first_name_user_last_name_alter_comment_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default=None, max_length=255, null=True, upload_to='images/'),
        ),
    ]
