# Generated by Django 4.1.6 on 2023-02-19 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_movie_image_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, default='06e4a455f25787fe099f7304316bf449_400x400-300x300.png', max_length=255, null=True, upload_to='images/', verbose_name='movie image'),
        ),
    ]
