# Generated by Django 4.1.6 on 2023-02-19 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, default='17-640x640.jpeg', max_length=255, null=True, upload_to='images/', verbose_name='movie image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='17-640x640.jpeg', max_length=255, null=True, upload_to='images/'),
        ),
    ]
