# Generated by Django 4.1.6 on 2023-02-19 03:34

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_order_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_value',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=1000, validators=[base.models.validate_non_negative], verbose_name='order_value'),
        ),
    ]
