# Generated by Django 4.1.6 on 2023-02-19 09:46

import base.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_product_remove_order_order_value_alter_order_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderManually',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_value', models.DecimalField(decimal_places=2, default=0.01, max_digits=1000, validators=[base.models.validate_non_negative], verbose_name='order_value')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordermanually', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
