# Generated by Django 4.1.6 on 2023-02-20 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_ordermanually'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDOPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todopage', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
